/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/alltogether.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/alltogether.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bespin.geometry} material={materials['Material.001']} position={[0, -6, 0]} />
      <mesh geometry={nodes.Alderaan.geometry} material={materials['Material.001']} position={[0, 6, 0]} />
      <mesh geometry={nodes.Dagobah.geometry} material={materials['Material.002']} position={[0, -3, 0]} />
      <mesh geometry={nodes.Endor.geometry} material={materials['Material.003']} position={[0, -9, 0]} />
      <mesh geometry={nodes.Hoth.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.YavinIV.geometry} material={materials['Material.005']} position={[0, 3, 0]} />
      <mesh geometry={nodes.tatooine.geometry} material={materials['Material.007']} position={[0, 9, 0]} />
    </group>
  )
}

useGLTF.preload('/alltogether.glb')
